version: '3'
services:
    nginx:
        container_name: "docker-nginx"
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - $PWD/public:/var/www/html
            - $PWD/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        container_name: "docker-php"
        image: php:7.2-fpm
        volumes:
            - $PWD/public:/var/www/html
            - $PWD/php/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

    mysql:
        container_name: "docker-mysql"
        image: mysql:5.7
        volumes:
            - $PWD/mysql/data:/var/lib/mysql
            - $PWD/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - $PWD/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        environment:
            MYSQL_ROOT_PASSWORD: mysql

    redis:
        container_name: "docker-redis"
        image: redis:latest
        command: ["redis-server", "/etc/redis.conf"]
        volumes:
            - $PWD/redis/redis.conf:/etc/redis.conf
        sysctls:
            net.core.somaxconn: 512

    portainer:
        container_name: "docker-port"
        image: portainer/portainer:latest
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:cached
            - $PWD/portainer/:/data:cached

